#define KEY_NUL         0x00
#define KEY_SOH         0x01
#define KEY_STX         0x02
#define KEY_ETX         0x03
#define KEY_EOT         0x04
#define KEY_ENQ         0x05
#define KEY_ACK         0x06
#define KEY_BEL         0x07
#define KEY_BS          0x08
#define KEY_TAB         0x09
#define KEY_LF			0x0A
#define KEY_VT   		0x0B
#define KEY_FF          0x0C
#define KEY_CR    		0x0D
#define KEY_SO          0x0E
#define KEY_SI          0x0F
#define KEY_DLE         0x10
#define KEY_DC1         0x11
#define KEY_DC2         0x12
#define KEY_DC3         0x13
#define KEY_DC4         0x14
#define KEY_NAK         0x15
#define KEY_SYN         0x16
#define KEY_ETB         0x17
#define KEY_CAN         0x18
#define KEY_EM          0x19
#define KEY_SUB         0x1A
#define KEY_ESC         0x1B
#define KEY_FS          0x1C
#define KEY_GS          0x1D
#define KEY_RS          0x1E
#define KEY_US          0x1F
#define KEY_SPACE       0x20

#define KEY_0 			0x30